name: Vite build

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            pages: write
        steps:
            - uses: actions/checkout@v7
            - uses: pnpm/action-setup@v6
              name: Install pnpm
              with:
                  version: latest
            - uses: actions/setup-node@v7
              with:
                  cache: pnpm
                  node-version: 24
            - run: pnpm install
            - run: pnpm build
            - uses: actions/upload-pages-artifact@v3
              with:
                  path: dist
            - uses: actions/deploy-pages@v4
              id: deployment
