name: Vite build + deploy to pages

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
              with:
                  submodules: true
            - uses: pnpm/action-setup@v6
              name: Install pnpm
              with:
                  version: latest
            - uses: actions/setup-node@v7
              with:
                  cache: pnpm
                  node-version: 24
            - run: pnpm install
            - run: pnpm build
            - uses: actions/upload-pages-artifact@v3
              with:
                  path: dist
    deploy:
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GH Pages
              id: deployment
              uses: actions/deploy-pages@v4
